[package]
name = "rvk"
version = "0.0.0"
authors = ["Artem Varaksa <aymfst@gmail.com>"]
readme = "README.md"
license = "MIT"
description = "Placeholder"

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"