[package]
name = "rvk"
version = "0.1.8"
authors = ["Artem Varaksa <aymfst@gmail.com>"]
readme = "README.md"
license = "MIT"
description = "Crate for accessing VK API"
repository = "https://github.com/u32i64/rvk"
keywords = ["vk", "api", "method"]
categories = ["api-bindings", "asynchronous"]

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
futures = "0.1"
tokio-core = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
url = "1.7"
serde_json = "1.0"
heck = "0.3"
